---
dependency:
  name: galaxy
#  options:
#    role-file: ./molecule/resources/playbooks/requirements.yml
driver:
  name: docker
#lint:
#  name: yamllint
#  enabled: false
platforms:
  - name: debianbuster
    image: jrei/systemd-debian:10
  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
  - name: ubuntu-focal-2004
    image: "ubuntu:focal"
  - name: ubuntu-groovy-2010
    image: "ubuntu:groovy"
#  - name: ubuntu-hirsute-2104
#    image: "ubuntu:hirsute"
  - name: fedora
    image: fedora:29
  - name: centos7
    image: centos:7
  - name: centos8
    image: centos:8    
provisioner:
  name: ansible
#  playbooks:
#    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint
    enabled: false
    options:
      x:
        - ANSIBLE0006
        - ANSIBLE0010
        - ANSIBLE0011
        - ANSIBLE0016
        - ANSIBLE0106
scenario:
  name: default
verifier:
  name: testinfra
  directory: ./../../tests/
#  additional_files_or_dirs:
#    - ../tests_vanilla/
#  lint:
#    name: flake8
